export const FORCE_RENDER = "FORCE_RENDER";
// LOGIN
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

// Create task modal
export const SET_CREATE_TASK_MODAL_ISOPEN = "SET_CREATE_TASK_MODAL_ISOPEN";
export const SET_CREATE_TASK_MODAL_SELECTED_MACHINE =
  "SET_CREATE_TASK_MODAL_SELECTED_MACHINE";
