const actionTypes = {
  FORCE_RENDER: "FORCE_RENDER",

  // Create task modal
  SET_CREATE_TASK_MODAL_ISOPEN: "SET_CREATE_TASK_MODAL_ISOPEN",
  SET_CREATE_TASK_MODAL_SELECTED_MACHINE:
    "SET_CREATE_TASK_MODAL_SELECTED_MACHINE",
};

export default actionTypes;
